create table product_details (
	id INT PRIMARY KEY,
	product_id INT,
	other_data VARCHAR(50),
    FOREIGN KEY (product_id) REFERENCES product(id)
);
insert into product_details (id, product_id, other_data) values (1, 15, 'Volkswagen');
insert into product_details (id, product_id, other_data) values (2, 79, 'Lexus');
insert into product_details (id, product_id, other_data) values (3, 44, 'Jeep');
insert into product_details (id, product_id, other_data) values (4, 91, 'Daewoo');
insert into product_details (id, product_id, other_data) values (5, 57, 'Volkswagen');
insert into product_details (id, product_id, other_data) values (6, 25, 'Cadillac');
insert into product_details (id, product_id, other_data) values (7, 93, 'Ford');
insert into product_details (id, product_id, other_data) values (8, 68, 'Lotus');
insert into product_details (id, product_id, other_data) values (9, 16, 'Dodge');
insert into product_details (id, product_id, other_data) values (10, 51, 'GMC');
insert into product_details (id, product_id, other_data) values (11, 84, 'GMC');
insert into product_details (id, product_id, other_data) values (12, 81, 'Mercedes-Benz');
insert into product_details (id, product_id, other_data) values (13, 96, 'Mercedes-Benz');
insert into product_details (id, product_id, other_data) values (14, 7, 'Honda');
insert into product_details (id, product_id, other_data) values (15, 27, 'Toyota');
insert into product_details (id, product_id, other_data) values (16, 100, 'Oldsmobile');
insert into product_details (id, product_id, other_data) values (17, 61, 'Dodge');
insert into product_details (id, product_id, other_data) values (18, 41, 'Lexus');
insert into product_details (id, product_id, other_data) values (19, 19, 'Chevrolet');
insert into product_details (id, product_id, other_data) values (20, 17, 'Hyundai');
insert into product_details (id, product_id, other_data) values (21, 88, 'Pontiac');
insert into product_details (id, product_id, other_data) values (22, 55, 'Pontiac');
insert into product_details (id, product_id, other_data) values (23, 76, 'Mercedes-Benz');
insert into product_details (id, product_id, other_data) values (24, 25, 'Audi');
insert into product_details (id, product_id, other_data) values (25, 73, 'Chevrolet');
insert into product_details (id, product_id, other_data) values (26, 32, 'Ford');
insert into product_details (id, product_id, other_data) values (27, 41, 'Saturn');
insert into product_details (id, product_id, other_data) values (28, 92, 'Chrysler');
insert into product_details (id, product_id, other_data) values (29, 48, 'Isuzu');
insert into product_details (id, product_id, other_data) values (30, 17, 'Chevrolet');
insert into product_details (id, product_id, other_data) values (31, 30, 'Oldsmobile');
insert into product_details (id, product_id, other_data) values (32, 3, 'Ford');
insert into product_details (id, product_id, other_data) values (33, 39, 'Mitsubishi');
insert into product_details (id, product_id, other_data) values (34, 15, 'Honda');
insert into product_details (id, product_id, other_data) values (35, 25, 'Chevrolet');
insert into product_details (id, product_id, other_data) values (36, 52, 'Nissan');
insert into product_details (id, product_id, other_data) values (37, 74, 'Plymouth');
insert into product_details (id, product_id, other_data) values (38, 74, 'Volkswagen');
insert into product_details (id, product_id, other_data) values (39, 85, 'Aston Martin');
insert into product_details (id, product_id, other_data) values (40, 8, 'Ford');
insert into product_details (id, product_id, other_data) values (41, 13, 'Oldsmobile');
insert into product_details (id, product_id, other_data) values (42, 29, 'Mazda');
insert into product_details (id, product_id, other_data) values (43, 3, 'Volvo');
insert into product_details (id, product_id, other_data) values (44, 63, 'Ford');
insert into product_details (id, product_id, other_data) values (45, 78, 'Ford');
insert into product_details (id, product_id, other_data) values (46, 41, 'Mitsubishi');
insert into product_details (id, product_id, other_data) values (47, 88, 'Porsche');
insert into product_details (id, product_id, other_data) values (48, 23, 'Volkswagen');
insert into product_details (id, product_id, other_data) values (49, 13, 'Chevrolet');
insert into product_details (id, product_id, other_data) values (50, 13, 'GMC');
insert into product_details (id, product_id, other_data) values (51, 8, 'Toyota');
insert into product_details (id, product_id, other_data) values (52, 11, 'Saturn');
insert into product_details (id, product_id, other_data) values (53, 71, 'Buick');
insert into product_details (id, product_id, other_data) values (54, 17, 'Lexus');
insert into product_details (id, product_id, other_data) values (55, 91, 'Chevrolet');
insert into product_details (id, product_id, other_data) values (56, 51, 'Aston Martin');
insert into product_details (id, product_id, other_data) values (57, 60, 'Dodge');
insert into product_details (id, product_id, other_data) values (58, 40, 'GMC');
insert into product_details (id, product_id, other_data) values (59, 78, 'Audi');
insert into product_details (id, product_id, other_data) values (60, 21, 'MINI');
insert into product_details (id, product_id, other_data) values (61, 52, 'Nissan');
insert into product_details (id, product_id, other_data) values (62, 84, 'Honda');
insert into product_details (id, product_id, other_data) values (63, 58, 'Chevrolet');
insert into product_details (id, product_id, other_data) values (64, 8, 'Mitsubishi');
insert into product_details (id, product_id, other_data) values (65, 44, 'Oldsmobile');
insert into product_details (id, product_id, other_data) values (66, 89, 'Toyota');
insert into product_details (id, product_id, other_data) values (67, 30, 'Jaguar');
insert into product_details (id, product_id, other_data) values (68, 3, 'Mitsubishi');
insert into product_details (id, product_id, other_data) values (69, 45, 'Volkswagen');
insert into product_details (id, product_id, other_data) values (70, 89, 'Oldsmobile');
insert into product_details (id, product_id, other_data) values (71, 36, 'Lincoln');
insert into product_details (id, product_id, other_data) values (72, 44, 'Honda');
insert into product_details (id, product_id, other_data) values (73, 68, 'Dodge');
insert into product_details (id, product_id, other_data) values (74, 55, 'GMC');
insert into product_details (id, product_id, other_data) values (75, 65, 'Subaru');
insert into product_details (id, product_id, other_data) values (76, 99, 'Kia');
insert into product_details (id, product_id, other_data) values (77, 16, 'Lexus');
insert into product_details (id, product_id, other_data) values (78, 36, 'Honda');
insert into product_details (id, product_id, other_data) values (79, 100, 'Pontiac');
insert into product_details (id, product_id, other_data) values (80, 66, 'Land Rover');
insert into product_details (id, product_id, other_data) values (81, 63, 'Hyundai');
insert into product_details (id, product_id, other_data) values (82, 61, 'Nissan');
insert into product_details (id, product_id, other_data) values (83, 68, 'Subaru');
insert into product_details (id, product_id, other_data) values (84, 40, 'Dodge');
insert into product_details (id, product_id, other_data) values (85, 47, 'Lotus');
insert into product_details (id, product_id, other_data) values (86, 17, 'Audi');
insert into product_details (id, product_id, other_data) values (87, 70, 'GMC');
insert into product_details (id, product_id, other_data) values (88, 77, 'Oldsmobile');
insert into product_details (id, product_id, other_data) values (89, 42, 'Pontiac');
insert into product_details (id, product_id, other_data) values (90, 71, 'Honda');
insert into product_details (id, product_id, other_data) values (91, 2, 'Lexus');
insert into product_details (id, product_id, other_data) values (92, 11, 'Cadillac');
insert into product_details (id, product_id, other_data) values (93, 67, 'Chevrolet');
insert into product_details (id, product_id, other_data) values (94, 15, 'Audi');
insert into product_details (id, product_id, other_data) values (95, 98, 'Subaru');
insert into product_details (id, product_id, other_data) values (96, 51, 'Land Rover');
insert into product_details (id, product_id, other_data) values (97, 65, 'Ford');
insert into product_details (id, product_id, other_data) values (98, 71, 'Mitsubishi');
insert into product_details (id, product_id, other_data) values (99, 29, 'GMC');
insert into product_details (id, product_id, other_data) values (100, 90, 'Suzuki');